[build]
  base = "client"
  publish = ".next"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  NEXT_PUBLIC_API_URL = "https://api.te.kg"
  NEXT_PUBLIC_SUPABASE_URL = "https://eacpkbrvpxhejgwyziwd.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVhY3BrYnJ2cHhoZWpnd3l6aXdkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MDE5NTk5NDAsImV4cCI6MjAxNzUzNTk0MH0.1CAOvhWWxHBzEQEbTJvRjFAEKTlX2-yWVnRzpg-VBMU"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' https://api.te.kg https://*.supabase.co; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://telegram.org https://*.telegram.org; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https://*.telegram.org; connect-src 'self' https://api.te.kg https://*.supabase.co wss://*.supabase.co https://telegram.org https://*.telegram.org;"

[dev]
  framework = "next"
  targetPort = 3000

# Настройки для разных окружений
[context.production]
  environment = { NODE_ENV = "production" }

[context.deploy-preview]
  environment = { NODE_ENV = "preview" }

[context.branch-deploy]
  environment = { NODE_ENV = "development" }
